# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  # Base directory

  - package-ecosystem: "composer"

    directory: "/"

    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"

    open-pull-requests-limit: 10

    assignees:
      - "mimmi20"

    labels:
      - "dependencies"

    versioning-strategy: "increase"

    target-branch: "master"

    commit-message:
      include: "scope"
      prefix: "composer"

    ignore:
      - dependency-name: "psr/container"
      - dependency-name: "psr/http-message"

    rebase-strategy: "auto"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "npm"

  - package-ecosystem: "npm"
    directory: "web/amplitude-ua-parser-js/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "npm"
    target-branch: "master"

  - package-ecosystem: "npm"
    directory: "web/bowser/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "npm"
    target-branch: "master"

  - package-ecosystem: "npm"
    directory: "web/browser-detect/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "npm"
    target-branch: "master"

  - package-ecosystem: "npm"
    directory: "web/detect-browser/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "npm"
    target-branch: "master"

  - package-ecosystem: "npm"
    directory: "web/device-detector/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "npm"
    target-branch: "master"

  - package-ecosystem: "npm"
    directory: "web/device-detector-node/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "npm"
    target-branch: "master"

  - package-ecosystem: "npm"
    directory: "web/express-useragent/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "npm"
    target-branch: "master"

  - package-ecosystem: "npm"
    directory: "web/fex-uadevice/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "npm"
    target-branch: "master"

  - package-ecosystem: "npm"
    directory: "web/financial-times-useragent_parser/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "npm"
    target-branch: "master"

  - package-ecosystem: "npm"
    directory: "web/hotoo-detector/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "npm"
    target-branch: "master"

  - package-ecosystem: "npm"
    directory: "web/journyio-user-agent-parser/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "npm"
    target-branch: "master"

  - package-ecosystem: "npm"
    directory: "web/node-device-detector/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "npm"
    target-branch: "master"

  - package-ecosystem: "npm"
    directory: "web/platformjs/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "npm"
    target-branch: "master"

  - package-ecosystem: "npm"
    directory: "web/ua-parser-js/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "npm"
    target-branch: "master"

  - package-ecosystem: "npm"
    directory: "web/vigour-ua/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "npm"
    target-branch: "master"

  - package-ecosystem: "npm"
    directory: "web/whichbrowser-js/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "npm"
    target-branch: "master"

  - package-ecosystem: "npm"
    directory: "web/woothee-js/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "npm"
    target-branch: "master"

  # actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    commit-message:
      prefix: "github-actions"
    ignore:
      - dependency-name: "mimmi20/ci"
      - dependency-name: "release-drafter/release-drafter"
