# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    target-branch: "master"
    commit-message:
      include: "scope"
      prefix: "composer"
#    ignore:
#      - dependency-name: infection/infection
#        versions:
#          - ">= 0"
#      - dependency-name: phpunit/phpunit
#        versions:
#          - ">= 0"
#      - dependency-name: symfony/finder
#        versions:
#          - ">= 0"
#      - dependency-name: laminas/laminas-diactoros
#        versions:
#          - ">= 0"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"
    commit-message:
      include: "scope"
      prefix: "github-actions"

  - package-ecosystem: "npm"
    directory: "web/3rd-eden/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"

  - package-ecosystem: "npm"
    directory: "web/bowser-js/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"

  - package-ecosystem: "composer"
    directory: "web/browscap/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"
    versioning-strategy: "increase"

  - package-ecosystem: "npm"
    directory: "web/browser-detect-js/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"

  - package-ecosystem: "composer"
    directory: "web/browser-detector/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"
    versioning-strategy: "increase"

  - package-ecosystem: "composer"
    directory: "web/cbschuld/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"
    versioning-strategy: "increase"

  - package-ecosystem: "npm"
    directory: "web/detect-browser-js/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"

  - package-ecosystem: "npm"
    directory: "web/device-detector-js/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"

  - package-ecosystem: "npm"
    directory: "web/device-detector-node-js/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"

  - package-ecosystem: "composer"
    directory: "web/donatj/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"
    versioning-strategy: "increase"

  - package-ecosystem: "composer"
    directory: "web/endorphin/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"
    versioning-strategy: "increase"

  - package-ecosystem: "npm"
    directory: "web/express-useragent-exposer/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"

  - package-ecosystem: "npm"
    directory: "web/express-useragent/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"

  - package-ecosystem: "npm"
    directory: "web/fex-uadevice/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"

  - package-ecosystem: "npm"
    directory: "web/hotoo-detector/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"

  - package-ecosystem: "composer"
    directory: "web/jenssegers-agent/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"
    versioning-strategy: "increase"

  - package-ecosystem: "composer"
    directory: "web/matomo/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"
    versioning-strategy: "increase"

  - package-ecosystem: "composer"
    directory: "web/sinergi/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"
    versioning-strategy: "increase"

  - package-ecosystem: "npm"
    directory: "web/ua-parser-js/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"

  - package-ecosystem: "composer"
    directory: "web/ua-parser-php/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"
    versioning-strategy: "increase"

  - package-ecosystem: "npm"
    directory: "web/vigour-ua/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"

  - package-ecosystem: "npm"
    directory: "web/which-browser-js/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"

  - package-ecosystem: "composer"
    directory: "web/which-browser-php/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"
    versioning-strategy: "increase"

  - package-ecosystem: "composer"
    directory: "web/wolfcast/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"
    versioning-strategy: "increase"

  - package-ecosystem: "npm"
    directory: "web/woothee-js/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"

  - package-ecosystem: "composer"
    directory: "web/woothee-php/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"
    versioning-strategy: "increase"

  - package-ecosystem: "composer"
    directory: "web/zsxsoft/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"
    versioning-strategy: "increase"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"
