# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  # Base directory

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    groups:
      security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"
      version-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "composer"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    groups:
      security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"
      version-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "npm"

  - package-ecosystem: "npm"
    directory: "web/amplitude-ua-parser-js/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "npm"
    target-branch: "master"

  - package-ecosystem: "npm"
    directory: "web/bowser/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "npm"
    target-branch: "master"

  - package-ecosystem: "composer"
    directory: "web/browscap-php/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "composer"

  - package-ecosystem: "npm"
    directory: "web/browser-detect/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "npm"
    target-branch: "master"

  - package-ecosystem: "composer"
    directory: "web/browser-detector/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "composer"

  - package-ecosystem: "composer"
    directory: "web/cbschuld/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"
    versioning-strategy: "increase"

  - package-ecosystem: "npm"
    directory: "web/crawler-detect/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "npm"
    target-branch: "master"

  - package-ecosystem: "npm"
    directory: "web/detect-browser/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "npm"
    target-branch: "master"

  - package-ecosystem: "npm"
    directory: "web/device-detector/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "npm"
    target-branch: "master"

  - package-ecosystem: "npm"
    directory: "web/device-detector-node/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "npm"
    target-branch: "master"

  - package-ecosystem: "composer"
    directory: "web/donatj/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "composer"

  - package-ecosystem: "composer"
    directory: "web/endorphin/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"
    versioning-strategy: "increase"

  - package-ecosystem: "npm"
    directory: "web/express-useragent/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "npm"
    target-branch: "master"

  - package-ecosystem: "npm"
    directory: "web/fex-uadevice/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "npm"
    target-branch: "master"

  - package-ecosystem: "npm"
    directory: "web/financial-times-useragent_parser/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "npm"
    target-branch: "master"

  - package-ecosystem: "npm"
    directory: "web/hotoo-detector/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "npm"
    target-branch: "master"

  - package-ecosystem: "composer"
    directory: "web/jenssegers-agent/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "composer"

  - package-ecosystem: "npm"
    directory: "web/journyio-user-agent-parser/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "npm"
    target-branch: "master"

  - package-ecosystem: "composer"
    directory: "web/matomo/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "composer"

  - package-ecosystem: "composer"
    directory: "web/mobile-detect/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "composer"

  - package-ecosystem: "npm"
    directory: "web/node-device-detector/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "npm"
    target-branch: "master"

  - package-ecosystem: "composer"
    directory: "web/php-get-browser/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "composer"

  - package-ecosystem: "npm"
    directory: "web/platformjs/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "npm"
    target-branch: "master"

  - package-ecosystem: "npm"
    directory: "web/ua-parser-js/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "npm"
    target-branch: "master"

  - package-ecosystem: "composer"
    directory: "web/ua-parser-php/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "composer"

  - package-ecosystem: "npm"
    directory: "web/vigour-ua/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "npm"
    target-branch: "master"

  - package-ecosystem: "npm"
    directory: "web/whichbrowser-js/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "npm"
    target-branch: "master"

  - package-ecosystem: "composer"
    directory: "web/whichbrowser-php/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "composer"

  - package-ecosystem: "composer"
    directory: "web/wolfcast/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "composer"

  - package-ecosystem: "npm"
    directory: "web/woothee-js/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "npm"
    target-branch: "master"

  - package-ecosystem: "composer"
    directory: "web/woothee-php/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    target-branch: "master"
    versioning-strategy: "increase"
    commit-message:
      include: "scope"
      prefix: "composer"

  # actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    reviewers:
      - "mimmi20"
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    commit-message:
      prefix: "github-actions"
    ignore:
      - dependency-name: "mimmi20/ci"
