template: |
  ## What’s Changed

  $CHANGES
exclude-labels:
  - duplicate
  - question
  - invalid
  - wontfix
categories:
  - title: '**💥 Breaking:**'
    labels:
      - 'BC Break'
  - title: '**🍰 Enhancements:**'
    labels:
      - 'enhancement'
  - title: '**🐞 Bugs:**'
    labels:
      - 'bug'
  - title: '**💀 Deprecated:**'
    labels:
      - 'deprecated'
  - title: '**🗑 Removed:**'
    labels:
      - 'removed'
  - title: '**🛡 Security:**'
    labels:
      - 'security'
  - title: '**🕸 Dependencies:**'
    labels:
      - 'dependencies'
  - title: '**🧹 Maintenance:**'
    labels:
      - 'maintenance'
      - 'new browser'
      - 'new device'
      - 'new engine'
      - 'new platform'
      - 'new test'
      - 'update browser'
      - 'update device'
      - 'update engine'
      - 'update platform'
      - 'update test'
  # other Labels to mimmi20/ua-comparator
  - title: '**📦 Documentation:**'
    labels:
      - 'documentation'

commitish: master
target_commitish: master
filter-by-commitish: true
