tools:
    php_cs_fixer: false
    php_code_sniffer:
        config:
            standard: "PSR2"

coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
            other:
                after_type_cast: true

checks:
    php:
        security_vulnerabilities: true
        no_underscore_prefix_in_properties: true
        no_underscore_prefix_in_methods: true
        no_exit: true
        no_eval: true
        no_error_suppression: true
        no_empty_statements: true
        no_debug_code: true
        no_commented_out_code: true
        newline_at_end_of_file: true
        deprecated_code_usage: true
        custom_coding_standard:
            ruleset_path: phpcs.xml
        code_rating: true
        catch_class_exists: true
        avoid_usage_of_logical_operators: true
        avoid_unnecessary_concatenation: true
        avoid_todo_comments: true
        avoid_superglobals: false
        avoid_perl_style_comments: true
        avoid_multiple_statements_on_same_line: true
        avoid_fixme_comments: true
        avoid_duplicate_types: true
        avoid_corrupting_byteorder_marks: true
        avoid_closing_tag: true
        avoid_aliased_php_functions: true
        align_assignments: true
        encourage_shallow_comparison: true
        encourage_single_quotes: true
        verify_property_names: true
        verify_argument_usable_as_reference: true
        verify_access_scope_valid: true
        variable_existence: true
        useless_calls: true
        uppercase_constants: true
        use_self_instead_of_fqcn: true
        unused_variables: true
        unused_properties: true
        unused_parameters: true
        unused_methods: true
        unreachable_code: true
        too_many_arguments: false
        simplify_boolean_return: true
        single_namespace_per_use: true
        require_scope_for_properties: true
        require_scope_for_methods: true
        require_php_tag_first: true
        psr2_switch_declaration: true
        psr2_class_declaration: true
        property_assignments: true
        precedence_mistakes: true
        precedence_in_conditions: true
        php5_style_constructor: true
        parse_doc_comments: true
        parameter_non_unique: true
        param_doc_comment_if_not_inferrable: true
        overriding_private_members: true
        overriding_parameter: true
        one_class_per_file: true
        no_unnecessary_if: true

build:
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=phpunit-coverage.xml'
                coverage:
                    file: 'phpunit-coverage.xml'
                    format: 'clover'
    environment:
        php:
            version: 7.1
